# Generated by Django 4.1 on 2022-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_project_issue_project_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
