# Generated by Django 4.1 on 2022-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="issue", name="title", field=models.CharField(max_length=100),
        ),
    ]
