# Generated by Django 4.1 on 2022-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_comment_description_alter_contributor_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
