# Generated by Django 4.1 on 2022-08-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_comment_description_alter_issue_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="author_pk", new_name="author_id",
        ),
        migrations.RenameField(
            model_name="comment", old_name="issue_pk", new_name="issue_id",
        ),
        migrations.RenameField(
            model_name="contributor", old_name="project_pk", new_name="project_id",
        ),
        migrations.RenameField(
            model_name="contributor", old_name="user_pk", new_name="user_id",
        ),
        migrations.RenameField(
            model_name="issue", old_name="assignee_pk", new_name="assignee_id",
        ),
        migrations.RenameField(
            model_name="issue", old_name="author_pk", new_name="author_id",
        ),
        migrations.RenameField(
            model_name="issue", old_name="project_pk", new_name="project_id",
        ),
    ]
